
 
#ecm_articles_admin:
#    path: /admin/articles
#    defaults: { _controller: ECMArticleBundle:Default:administrationArticles }

ecm_articles_show_by_menu:
    path: /ecm/{titreMenu}
    defaults: { _controller: ECMArticleBundle:Default:showArticlesByMenu }
    
ecm_articles_show_by_util:
    path: user/articles/
    defaults: { _controller: ECMArticleBundle:Article:getArticlesByUser }   
    
#article_create:
#    path: /ecm/AjoutArticle
#    defaults: { _controller: ECMArticleBundle:Article:newAction }


#ecm_article_admin_modifier:
#    path: /admin/article/{id}
#    defaults: { _controller: ECMArticleBundle:Default:modifier }
#    requirements:
#        format: /d+

article:
    path:     /ecm/article
    defaults: { _controller: "ECMArticleBundle:Article:index" }

article_show:
    path:      user/article/{id}/show
    defaults: { _controller: "ECMArticleBundle:Article:show" }

article_new:
    path:      user/article/new
    defaults: { _controller: "ECMArticleBundle:Article:new" }

article_create:
    path:      user/article/create
    defaults: { _controller: "ECMArticleBundle:Article:create" }
    requirements: { _method: post }

article_edit:
    path:      user/article/{id}/edit
    defaults: { _controller: "ECMArticleBundle:Article:edit" }
    
   

article_update:
    path:      user/article/{id}/update
    defaults: { _controller: "ECMArticleBundle:Article:update" }
    requirements: { _method: post|put }

article_delete:
    path:      user/article/{id}/delete
    defaults: { _controller: "ECMArticleBundle:Article:delete" }
    requirements: { _method: post|delete }
    
    
article_user:
    path:     /ecm/article_user
    defaults: { _controller: "ECMArticleBundle:ArticleAdmin:index" }

article_show_user:
    path:      ecm/article_user/{id}/show
    defaults: { _controller: "ECMArticleBundle:ArticleAdmin:show" }

article_new_user:
    path:      ecm/article_user/new
    defaults: { _controller: "ECMArticleBundle:ArticleAdmin:new" }

article_create_user:
    path:      ecm/article_user/create
    defaults: { _controller: "ECMArticleBundle:ArticleAdmin:create" }
    requirements: { _method: post }

article_update_user:
    path:      ecm/article_user/{id}/update
    defaults: { _controller: "ECMArticleBundle:ArticleAdmin:update" }
    requirements: { _method: post|put }

article_delete_user:
    path:      ecm/article_user/{id}/delete
    defaults: { _controller: "ECMArticleBundle:ArticleAdmin:delete" }
    requirements: { _method: post|delete }
        
    
article_edit_user:
    path:      ecm/article_user/{id}/edit
    defaults: { _controller: "ECMArticleBundle:ArticleAdmin:edit" }

      