
 
#ecm_articles_admin:
#    path: /admin/articles
#    defaults: { _controller: ECMArticleBundle:Default:administrationArticles }

ecm_articles_show_by_menu:
    path: /ecm/{titreMenu}
    defaults: { _controller: ECMArticleBundle:Default:showArticlesByMenu }


#ecm_article_admin_modifier:
#    path: /admin/article/{id}
#    defaults: { _controller: ECMArticleBundle:Default:modifier }
#    requirements:
#        format: /d+
