parameters:

services:


    sonata.admin.article:
        class: ECM\Bundle\ArticleBundle\Admin\ArticleAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Contenu"
              label: "Articles"
        arguments:
            - ~
            - ECM\Bundle\ArticleBundle\Entity\Article
            - ~

