ecm_admin:
    resource: "@ECMAdminBundle/Resources/config/routing.yml"
    prefix:   /

ecm_module:
    resource: "@ECMModuleBundle/Resources/config/routing.yml"
    prefix:   /

ECMModuleBundle_admin_sponsor:
    resource: "@ECMModuleBundle/Resources/config/routing/sponsor.yml"
    prefix:   /admin/sponsor


ecm_article:
    resource: "@ECMArticleBundle/Resources/config/routing.yml"
    prefix:   /

ecm_user:
    resource: "@ECMUserBundle/Resources/config/routing.yml"
    prefix:   /

ecm_home:
    resource: "@ECMHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


