ecm_shop:
    resource: "@ECMShopBundle/Resources/config/routing.yml"
    prefix:   /

ecm_admin:
    resource: "@ECMAdminBundle/Resources/config/routing.yml"
    prefix:   /

ecm_module:
    resource: "@ECMModuleBundle/Resources/config/routing.yml"
    prefix:   /



ecm_article:
    resource: "@ECMArticleBundle/Resources/config/routing.yml"
    prefix:   /

ecm_user:
    resource: "@ECMUserBundle/Resources/config/routing.yml"
    prefix:   /

ecm_home:
    resource: "@ECMHomeBundle/Resources/config/routing.yml"
    prefix:   /
    
# app/config/routing.yml
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    



gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
#sonata_cache_cache:
#    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
#    prefix: /
#
#sonata_page_exceptions:
#    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
#    prefix: /
#
#sonata_page_cache:
#    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
#    prefix: /