ecm_user:
    resource: "@ECMUserBundle/Resources/config/routing.yml"
    prefix:   /

ecm_home:
    resource: "@ECMHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

