ecm_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: ECMUserBundle:Default:index }

ecm_user_login:
    path: /connexion
    defaults: { _controller: ECMUserBundle:Default:login }
