parameters:
#    ecm_user.example.class: ECM\Bundle\UserBundle\Example

services:
    acme_user.registration.form.type:
        class: ECM\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: ecm_user_registration }