<?php

namespace ECM\Bundle\ModuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{

    public function getSubMenus($menuParent){
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM ECMModuleBundle:Menu m WHERE m.parent = :parent')
            ->setParameter('parent', $menuParent)
        ->getResult();
    }

    public function getMenusOnly()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM ECMModuleBundle:Menu m WHERE NOT m INSTANCE OF ECMModuleBundle:SubMenu')
            ->getResult();
    }



}
