<?php

namespace ECM\Bundle\ModuleBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use ECM\Bundle\ModuleBundle\ECMModuleBundle\Sponsor;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * SponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorRepository extends EntityRepository
{
    public function ajouterSponsor(Sponsor $sponsor){
        $rsm = new ResultSetMapping();
        
        $titre = $sponsor->getTitre();
        $urlImage = $sponsor->getUrlImage();
        $lien = $sponsor->getLien();
        $ordre = $sponsor->getOrdre();
        return $this->getEntityManager()
                ->createNativeQuery('CALL ordre_proc (\''.$titre.'\',\''.$urlImage.'\',\''.$lien.'\',\''.$ordre.'\')', $rsm)
                ->getResult();
    }
}
