<?php

namespace ECM\Bundle\ModuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubMenuRepository extends EntityRepository
{
}
