<?php

namespace ECM\Bundle\ArticleBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends PublicationRepository
{

    public function getArticlesByMenu(String $menu)
    {
        $query = 'SELECT a, m FROM ECMArticleBundle:Article a JOIN a.menu m';
        $this->_em->createQuery()->getResult();
    }

    public function getArticlesByMenuAndByEtat($menu)
    {
        $query = $this->_em->createQueryBuilder('a')
            ->select('a')
            ->from('ECMArticleBundle:Article', 'a')
            ->where('a.menu = :menu')
            ->andWhere('a.etat = 2')
            ->setParameter('menu', $menu)
            ->getQuery();

        return $query->getResult();

    }

}
