<?php

namespace ECM\Bundle\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{

    public function getArticlesByMenu(String $menu)
    {
        $query = 'SELECT a, m FROM ECMArticleBundle:Article a JOIN a.menu m';
        $this->_em->createQuery()->getResult();
    }

    public function getArticlesByMenuAndByEtat($menu)
    {
        //$query = 'SELECT a, m FROM ECMArticleBundle:Article a JOIN a.menu m WHERE a.etat = 1 and a.menu = :menu';
        //return $this->_em->createQuery($query)->setParameter('menu', $menu)->getResult();

        $query = $this->_em->createQueryBuilder('p')
            ->select('p')
            ->from('ECMArticleBundle:Publication', 'p')
            ->where('p.menu = :menu')
            ->andWhere('p.etat = 2')
            ->setParameter('menu', $menu)
            ->getQuery();

        return $query->getResult();

    }

}