parameters:
#    ecm_admin.example.class: ECM\Bundle\AdminBundle\Example

services:
#    ecm_admin.example:
#        class: %ecm_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ecm_admin.menu_builder:
        class: ECM\Bundle\AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    ecm_admin.menu.mainAdmin:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: ecm_admin.menu_builder
        factory_method: createMainAdminMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: mainAdmin }