FOS\UserBundle\Model\User:
    properties:
        email:
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
            - Email:
                message: fos_user.email.invalid            
        plainPassword:
            - NotBlank:
                message: fos_user.email.blank
            - Length:
                min: 6
                minMessage: fos_user.password.short
                max: 255
                maxMessage: fos_user.password.long            
                groups: [ "my_registration", "my_profile", "ResetPassword", "ChangePassword"]
        username:
            - Length:
                min: 3
                minMessage: fos_user.username.short
                max: 25
                maxMessage: fos_user.username.long