
ecm_shop_allProduct:
    path:     /shop/
    defaults: { _controller: ECMShopBundle:Produit:index }
    
ecm_shop_ProductById:
    path:     /shop/produit/{id}
    defaults: { _controller: ECMShopBundle:Produit:show }