parameters:
#    ecm_module.example.class: ECM\Bundle\ModuleBundle\Example

services:
#    ecm_module.example:
#        class: %ecm_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
