parameters:
#    ecm_module.example.class: ECM\Bundle\ModuleBundle\Example

services:
#    ecm_module.example:
#        class: %ecm_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.sponsor:
        class: ECM\Bundle\ModuleBundle\Admin\SponsorAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Modules"
              label: "Sponsors"
        arguments:
            - ~
            - ECM\Bundle\ModuleBundle\Entity\Sponsor
            - 'PixSortableBehaviorBundle:SortableAdmin' # define the new controller via the third argument
        calls:
            - [setContainer, [@service_container]]
            - [setPositionService, [@pix_sortable_behavior.position]]



    ecm_module.admin.menu:
        class: ECM\Bundle\ModuleBundle\Admin\MenuAdmin
        arguments: [~, ECM\Bundle\ModuleBundle\Entity\Menu, ECMModuleBundle:MenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Modules, label: Menus}
        calls:
            - [setSubClasses, [{ Menu:"ECM\Bundle\ModuleBundle\Entity\Menu", Sous-menu:"ECM\Bundle\ModuleBundle\Entity\SubMenu"}]]
