parameters: ~

services:
    sonata.admin.sponsor:
        class: ECM\Bundle\ModuleBundle\Admin\SponsorAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Modules"
              label: "Sponsors"
        arguments:
            - ~
            - ECM\Bundle\ModuleBundle\Entity\Sponsor
            - 'PixSortableBehaviorBundle:SortableAdmin' # define the new controller via the third argument
        calls:
            - [setContainer, [@service_container]]
            - [setPositionService, [@pix_sortable_behavior.position]]



    ecm_module.admin.menu:
        class: ECM\Bundle\ModuleBundle\Admin\MenuAdmin
        arguments: [~, ECM\Bundle\ModuleBundle\Entity\Menu, ECMModuleBundle:MenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Modules, label: Menus}
        calls:
            - [setSubClasses, [{ Menu:"ECM\Bundle\ModuleBundle\Entity\Menu", Sous-menu:"ECM\Bundle\ModuleBundle\Entity\SubMenu"}]]


    sonata.admin.image:
            class: ECM\Bundle\ModuleBundle\Admin\ImageAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "Modules"
                  label: "Chargement Images"
            arguments:
                - ~
                - ECM\Bundle\ModuleBundle\Entity\Image
                - ~
            calls:
                - [setTemplates, [{outer_list_rows_mosaic:"SonataMediaBundle:MediaAdmin:list_outer_rows_mosaic.html.twig"}]]