# src/ECM/ModuleBundle/Resources/config/validation.yml
ECM\ModuleBundle\Entity\Sponsor:
    properties:
        ordre:
            - Range:
                min: 0
                minMessage: Entrez un nombre positif.