ecm_home_homepage:
    path:     /
    defaults: { _controller: ECMHomeBundle:Default:index }
ecm_home_contact:
    path: /contact
    defaults: { _controller: ECMHomeBundle:Default:contact }
ecm_home_horaires:
    path: /horaires
    defaults: { _controller: ECMHomeBundle:Default:horaires }
ecm_home_tarifs:
    path: /tarifs-2014-2015
    defaults: { _controller: ECMHomeBundle:Default:tarifs }
ecm_home_responsables:
    path: /responsables
    defaults: { _controller: ECMHomeBundle:Default:responsables }
ecm_admin_home:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ECMHomeBundle:Default:administration.html.twig'
        
