parameters:
#    ecm_home.example.class: ECM\Bundle\HomeBundle\Example

services:
#    ecm_home.example:
#        class: %ecm_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ecm_home.menus.container:
        class: ECM\Bundle\HomeBundle\MenusContainer\MenusContainer
        arguments: ["@service_container"]


    ecm_home.menu_builder:
        class: ECM\Bundle\HomeBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@service_container"]

    ecm_home.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: ecm_home.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main }
            
    ecm_home.menu.admin:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: ecm_home.menu_builder
        factory_method: createAdminMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: admin }
            
    ecm_home.menu.anonymous:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: ecm_home.menu_builder
        factory_method: createAnonymousMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: anonymous }
            
    ecm_home.menu.user:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: ecm_home.menu_builder
        factory_method: createUserMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: user }


    ecm_home.menu.generated:
            class: Knp\Menu\MenuItem # the service definition requires setting the class
            factory_service: ecm_home.menu_builder
            factory_method: generateMenu
            arguments: ["@request"]
            scope: request # needed as we have the request as a dependency here
            tags:
                - { name: knp_menu.menu, alias: generated }